services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:latest
    container_name: teleport
    restart: unless-stopped
    ports:
      - "3022:3022"   # SSH proxy port
      - "3023:3023"   # SSH node port
      - "3025:3025"   # Auth service
      - "3080:3080"   # Web UI
    volumes:
      - ./teleport-data:/var/lib/teleport
      - ./teleport.yaml:/etc/teleport.yaml
    command: start
